### ISSUE TITLE
Image not rendering correctly

### ISSUE THREAD

**Issue by kelseycaraballo** [Kozea/CairoSVG#73] opened 2015-09-10 23:19 UTC
![hello](https://cloud.githubusercontent.com/assets/12041087/9803418/062ed01a-57e8-11e5-9eff-9045cac2b165.png)

When trying to convert my svg file (not shown, due to incompatibility with attaching to github) to a png and pdf the words do not format correctly and seem to write on top of each other. How do you fix this error?

**Comment by liZe** [comment] 2015-09-11 06:42
It looks like #71: if you're using OSX, this bug is caused by Cairo and is already fixed in Cairo's repository. You can try to render this file on another OS (or paste it on pastebin for example if you want me to try).

**Comment by s1113950** [comment] 2015-10-02 23:10
bump. (Can be caused with http://samples.fileformat.info/format/svg/sample/1f34368ab03b47e5a415c72f8a54681c/ISO_12233-reschart.svg?AWSAccessKeyId=0V91BEFA7GM093MEVMG2&Signature=EcQfaryhUdhX1ywNFCJNfxqsna8%3D&Expires=1443825963 )

**Comment by liZe** [comment] 2015-10-03 11:52
@s1113950 Please read my message above. I bet you're using OSX. It's a bug in Cairo that's fixed in their git repository.

**Comment by liZe** [comment] 2015-10-26 17:35
No news is good news!

**Closed by liZe** 2015-10-26 17:35 UTC
Labels: bug
