### ISSUE TITLE
Font rendering discrepancy between PDF and PNG versions 

### ISSUE THREAD

**Issue by Alphare** [Kozea/CairoSVG#167] opened 2017-11-28 10:32 UTC
Hi, it's me again.
I have a somewhat contrived example, I'm sorry in advance.

I'm using `CairoSVG` to render text in PNG for an online editor, this way I always get the same client-side result. When the user is done with their work of positioning elements, text, images, etc., I export the whole document to PDF.

The text -> PNG conversion happens in an SVG empty canvas, then is cropped to the text's bounding box (except on the left, to keep the font initial margin) using Pillow. 

The PDF render happens after a critical step: the PNG text-images are transformed back into text nodes using the exact same information that was used to create them in the first place. Their `transform: translate` attribute is adjusted: add the text-image's rendered height to the `y` coordinate to account for the baseline being at the bottom.

**Client side**
![cairo_client_side](https://user-images.githubusercontent.com/9445758/33314240-53241772-d42d-11e7-86fe-af6a79f8fd72.png)

**PDF render**
![cairo_pdf_render](https://user-images.githubusercontent.com/9445758/33314264-64aca694-d42d-11e7-8f6e-e29502c8197e.png)

I have put markers at the rightmost edges of the document to show that the PDF does not shrink horizontally.
I'm using `ComicSansMS` (I know) with a `font-size` of `30` (no units) at the top right and `DejaVuSans` with a `font-size` of `30` (no units) at the bottom right.
**I've noticed that using a font of `29` will yield identical results (I think?).**

I hope my explanations are clear... if not I will try to do better. :smile:

**Comment by liZe** [comment] 2018-01-03 14:44
Yes, the text is rendered differently because of [hinting](https://en.wikipedia.org/wiki/Font_hinting), a feature that's not yet supported by CairoSVG and will probably never be :cry:. This issue is then a duplicate of (huge) #113.

**Closed by liZe** 2018-01-03 14:44 UTC

**Comment by Alphare** [comment] 2018-01-03 15:30
Ah, this is sad news indeed. So, because PDF renders the text using vector graphics and PNG is raster, I cannot get the same result?
Thank you again.

**Comment by liZe** [comment] 2018-01-03 15:34
> Ah, this is sad news indeed.

Indeed…

> So, because PDF renders the text using vector graphics and PNG is raster, I cannot get the same result?

That's exactly the problem. There's probably a way to hack in CairoSVG the way hinting is currently handled by Cairo depending on the output format, but without Pango won't be more than an awful hack.

**Comment by Alphare** [comment] 2018-01-03 15:44
Is there really no Python solution of going about this issue (yet)? I cannot be mad at anyone but me for not building said solution, that said. :D

**Comment by liZe** [comment] 2018-01-03 23:27
> Is there really no Python solution of going about this issue (yet)? I cannot be mad at anyone but me for not building said solution, that said. :D

I was wrong. There is a quite clean solution (I hope): you can set the `text-rendering` property to `geometricPrecision` and hope to get the result you want. It will disable hinting even for raster output formats.

(I don't remember ever adding this feature, but it's been added 420b65d5 :open_mouth:)

(Hi @Alphare! I didn't recognize you until now!)

**Comment by Alphare** [comment] 2018-01-10 15:39
Aaaaaaaaaaaaah that just solved my problem, this is fantastic :D
Thank you so much. (Hi @liZe! :D)
