### ISSUE TITLE
Weird rendering artefects and objects split in half (probably error at import time)

### ISSUE THREAD

**Issue by leleogere** [Kozea/CairoSVG#431] opened 2024-11-04 14:00 UTC
I'm struggling to convert a SVG file into a PNG.

Here is the SVG file:
![Image](https://github.com/user-attachments/assets/4ff5a5f7-f260-43ff-a122-86736bc8e539)

However, when rendering to PNG, here is the resulting file:
![Image](https://github.com/user-attachments/assets/8940398f-86da-4bd3-9d61-1d9dfd734bfe)

All objects seem to be cut in half for some reason. The issue is likely in the import part, as it results in this whatever the export format I choose. It even happens when converting from SVG to SVG (which should result in the same file): 
```bash
cairosvg test.svg -o test2.svg
```

**Comment by liZe** [comment] 2024-11-04 17:35
Thanks for the report. It’s actually a duplicate of #300, there’s a workaround but no fix yet.

**Closed by liZe** 2024-11-04 17:35 UTC

**Comment by leleogere** [comment] 2024-11-04 20:34
I had a quick look at existing issues but wasn't able to spot this one, the workaround is perfect thank you!
