### ISSUE TITLE
Svg with data URI embedded image losing image after conversion

### ISSUE THREAD

**Issue by artfulinfo** [Kozea/CairoSVG#387] opened 2023-04-22 23:46 UTC
Hello

After constructing an SVG with the following format:
```
svg = """\
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="{} {} {w} {h}" width="{w}" height="{h}">
    <path id="cropPath" d="{d}" />
    <clipPath id="crop">
        <use xlink:href="#cropPath" />
    </clipPath>
    <image xlink:href="data:image/{ext};base64,{encoded}" clip-path="url(#crop)"/>
</svg>
""".format(xmin, ymin, w=width, h=height, d=path.d(), ext=ext, encoded=encoded)
```
After converting with:
```
cairosvg.svg2png(
            bytestring=svg, write_to=f'./{p}.png', background_color=None, unsafe=True)
```
It returns a black filled version of the shape cropped with the clipPath, but the image is not kept. After searching through some of the other issues, I attempted to install the other dependencies recommended (Pillow and the css specific ones); switching to using xlink:href rather than href and enabling unsafe mode, with no success.
I think the docs mentioned support of all of the approaches I'm using in the svg construction, and I have run out of ideas to try.
I've confirmed saving the exact same string to disk with the below works fine as expected:
```
with open(f'./{p}.svg', 'w') as file:
            file.write(svg)
```
To test, I checked what the `svg2svg` output was and no image is present:
```
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="120pt" height="100.8pt" viewBox="0 0 120 100.8" version="1.1">
<g id="surface41">
<path style=" stroke:none;fill-rule:nonzero;fill:rgb(0%,0%,0%);fill-opacity:1;" d="M 0 0 L 112.5 0 C 112.5 0 129.375 47.25 112.5 37.800781 C 95.625 28.351562 95.625 66.148438 112.5 56.699219 C 129.375 47.25 112.5 94.5 112.5 94.5 C 112.5 94.5 56.25 108.675781 67.5 94.5 C 78.75 80.324219 33.75 80.324219 45 94.5 C 56.25 108.675781 0 94.5 0 94.5 L 0 0 "/>
</g>
</svg>
```

**Comment by liZe** [comment] 2023-04-23 06:52
Hi,

Is this a duplicate of #383?

**Comment by artfulinfo** [comment] 2023-04-23 09:55
In my case it does not work regardless of whether unsafe flag is enabled or not. But could potentially be related. Is there any more information I can provide to help that I left out in the first comment?

**Comment by liZe** [comment] 2023-04-23 16:41
> Is there any more information I can provide to help that I left out in the first comment?

Yes. Could you please share a SVG file generated from your template? If it contains personal data you don’t want to share publicly, you can send a mail.

**Comment by artfulinfo** [comment] 2023-04-23 17:11
Sure thing, just shared over email

**Closed** 2023-04-29 11:57 UTC

**Comment by liZe** [comment] 2023-04-29 12:25
It’s fixed, feedback is welcome!
