### ISSUE TITLE
Incorrect conversion from SVG to PDF

### ISSUE THREAD

**Issue by vanniktech** [Kozea/CairoSVG#374] opened 2022-12-26 11:44 UTC
When using `cairosvg ic_time.svg -s 1.5 -o ic_time.pdf` with cairosvg 2.5.2 I get the following image:

<img width="949" alt="Screen Shot 2022-12-26 at 12 41 44" src="https://user-images.githubusercontent.com/5759366/209545080-6a758f9c-568f-402c-8da5-078071319835.png">

Note though that the conversion is somehow wrong since in the original image there's no bulk: ![ic_time](https://user-images.githubusercontent.com/5759366/209545108-bc50380e-0c12-40ac-b2c4-d17fc78d72c3.svg)

**Comment by liZe** [comment] 2022-12-27 11:22
Hi!

Thanks for the report.

It’s actually a duplicate of #346, it’s definitely time to release a new version…

**Closed** 2022-12-27 11:22 UTC
