### ISSUE TITLE
Error while installing Cairosvg on Mac

### ISSUE THREAD

**Issue by mayanrajesh** [Kozea/CairoSVG#314] opened 2021-02-19 22:48 UTC
```
ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bk/8179nfk53zg6pkfsgmsdcs780000gn/T/pip-install-8xlxs2ip/cairocffi/setup.py'"'"'; __file__='"'"'/private/var/folders/bk/8179nfk53zg6pkfsgmsdcs780000gn/T/pip-install-8xlxs2ip/cairocffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/bk/8179nfk53zg6pkfsgmsdcs780000gn/T/pip-install-8xlxs2ip/cairocffi/
    Complete output (25 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/bk/8179nfk53zg6pkfsgmsdcs780000gn/T/pip-install-8xlxs2ip/cairocffi/setup.py", line 10, in <module>
        setup(
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/dist.py", line 429, in __init__
        _Distribution.__init__(self, {
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/dist.py", line 721, in finalize_options
        ep(self)
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/dist.py", line 728, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/private/var/folders/bk/8179nfk53zg6pkfsgmsdcs780000gn/T/pip-install-8xlxs2ip/cairocffi/.eggs/cffi-1.14.5-py3.9-macosx-10.9-x86_64.egg/cffi/setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/private/var/folders/bk/8179nfk53zg6pkfsgmsdcs780000gn/T/pip-install-8xlxs2ip/cairocffi/.eggs/cffi-1.14.5-py3.9-macosx-10.9-x86_64.egg/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/private/var/folders/bk/8179nfk53zg6pkfsgmsdcs780000gn/T/pip-install-8xlxs2ip/cairocffi/.eggs/cffi-1.14.5-py3.9-macosx-10.9-x86_64.egg/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "cairocffi/ffi_build.py", line 28, in <module>
        ffi.cdef(constants._CAIRO_HEADERS)
    AttributeError: module 'constants' has no attribute '_CAIRO_HEADERS'
    ----------------------------------------
```

**Comment by liZe** [comment] 2021-02-20 12:33
Thanks for your report.

That’s actually a duplicate of Kozea/cairocffi#176, we can continue the discussion there.

**Closed by liZe** 2021-02-20 12:33 UTC
