### ISSUE TITLE
Cairo SVG 2.3.0 fails conversion of svg to pdf

### ISSUE THREAD

**Issue by wvalcke** [Kozea/CairoSVG#236] opened 2019-04-15 16:16 UTC
Using this simple svg example

[testje.zip](https://github.com/Kozea/CairoSVG/files/3081109/testje.zip)

It fails to convert.
the problem is with the xlink:href="#Port"

**Comment by wvalcke** [comment] 2019-04-15 16:30
I have the same problem when using matplotlib 3.0.3 and generating a simple plot and saving it to SVG format.

**Comment by wvalcke** [comment] 2019-04-15 16:45
Seems to be problem like described here: (and closed)
Issue with parsing of SVG <use> element #134

**Comment by liZe** [comment] 2019-04-15 16:48
Hello!

Your example works for me with version 2.3.0. Could you please provide the whole traceback?

**Comment by wvalcke** [comment] 2019-04-16 11:46
Hello,

The command i'm using is the following

cairosvg testje.svg -o testje.pdf 

see traceback.txt for the error details, the list.txt shows the installed python packages and versions.

For the moment this is all tested under Windows 10. If you want i can do the same under Linux.

[traceback.txt](https://github.com/Kozea/CairoSVG/files/3084748/traceback.txt)
[list.txt](https://github.com/Kozea/CairoSVG/files/3084749/list.txt)

Thanks !

**Comment by wvalcke** [comment] 2019-04-16 11:52
Hello,

Some more information, i did the same test under Linux.
And here everything works!
It must have something to do with Windows 10.
I also did the test with an SVG generated from matplotlib, and this worked as well under Linux.

**Comment by liZe** [comment] 2019-04-18 11:55
Oh, I'm stupid, that's a duplicate of (already fixed) #234. I'll release a new version with this fix today.

**Closed** 2019-04-18 12:21 UTC
