### ISSUE TITLE
Fatal error reading PNG image file: IDAT: CRC error when using XViewer / Safari

### ISSUE THREAD

**Issue by Alphare** [Kozea/CairoSVG#173] opened 2018-01-25 09:01 UTC
Hi, me again! :smiley: 

PNG error on open when using XViewer (ImageViewer in Linux Mint) with the following error:

`Fatal error reading PNG image file: IDAT: CRC error`

I found this bug when opening certain PNGs built by `CairoSVG` in Safari 10.1 using High Sierra, although Safari did not give me an error message. Every other relevant browser (IE11, Edge, Chrome, Firefox) has no issues opening those.

![b744e48ea8794d33ac4486662de88e68](https://user-images.githubusercontent.com/9445758/35379395-4681878c-01b6-11e8-857c-1e3f4b312959.png)

![2393011eb2af457e85757dbe81203dd2 1](https://user-images.githubusercontent.com/9445758/35379415-4d2d23ca-01b6-11e8-9a21-359e1b9d95fa.png)

Here are two examples, created using `svg_to_png` with the bytestring parameter.

**Comment by Alphare** [comment] 2018-01-25 09:06
Update: When opening the image then saving it using Pillow, the error goes away.

```
from PIL import Image
i = Image.open('faulty_png.png')
i.save('good.png')
```

**Comment by liZe** [comment] 2018-01-26 00:00
These PNG files are broken for me too. As I'm pretty sure that Cairo generates correct PNG files, I suppose that the problem is in the way generated files are written on the disk. Could you try to reproduce the problem with the CLI? If you can't, then there's probably something wrong with your file descriptors when you save the generated files.

If you also have the problem with the CLI, then there's something wrong with Cairo. If you use 1.14.12, you may have hit [this bug](https://bugs.freedesktop.org/show_bug.cgi?id=104325) that's already fixed in master but not released yet.

**Comment by Alphare** [comment] 2018-01-26 09:34
After some investigation, it appears that the bug stems from a resize method that is sometimes used in my code that has nothing to do with Cairo. You can close this issue, thanks for helping me out

**Comment by liZe** [comment] 2018-01-26 13:01
> After some investigation, it appears that the bug stems from a resize method that is sometimes used in my code that has nothing to do with Cairo.

Good news, thanks!

**Closed by liZe** 2018-01-26 13:01 UTC
