### ISSUE TITLE
cairosvg svg2png delivers broken pngs with svg files generated verovio

### ISSUE THREAD

**Issue by mxordn** [Kozea/CairoSVG#325] opened 2021-05-15 22:24 UTC
The conversion to png from svgs genereated by the [verovio toolkit](https://www.verovio.org/) seems to generate some „half rendered“ pngs. The png shows only one half of all the elements that are integrated as symbol tags.
An example of a verovio svg and the result in png can be found in [this stackoverflow question](https://stackoverflow.com/questions/67545632/cairosvg-producing-half-rendered-png-output).

I'd be glad to use cairosvg from python context to convert these verovio scores. Would be a nice workflow. Any help or suggestions are highly appreciated.

**Comment by liZe** [comment] 2021-05-16 10:11
Hello!

Thanks for the report. It’s actually a duplicate of #300. Unfortunately, there’s no easy fix for this bug. You’ll find a workaround in the comments, until we find a real fix.

**Closed by liZe** 2021-05-16 10:11 UTC
